<a href="https://colab.research.google.com/github/dileepchandhra/Solar-dryer/blob/main/GUAVA_NC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MINI PROJECT/Guava-nc.csv')
df.head()
df['DRYING RATE'] = df['DRYING RATE'].fillna(df['DRYING RATE'].mean())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TIME               20 non-null     int64
 1   MASS               20 non-null     float64
 2   TEMPERATURE INLET  20 non-null     int64
 3   MOISTURE CONTENT   20 non-null     float64
 4   MOISTURE RATIO     20 non-null     float64
 5   DRY MASS           20 non-null     float64
 6   DRYING RATE        20 non-null     float64
dtypes: float64(5), int64(2)
memory usage: 1.2 KB

In [ ]:
df.describe()

,TIME,MASS,TEMPERATURE INLET,MOISTURE CONTENT,MOISTURE RATIO,DRY MASS,DRYING RATE
count,20.00000,20.000000,20.000000,20.000000,20.000000,2.000000e+01,20.000000
mean,9.50000,331.110000,52.950000,1.704962,0.308005,1.224084e+02,0.290056
std,5.91608,215.402062,10.718773,1.759700,0.317894,1.458003e-14,0.286177
min,0.00000,125.400000,34.000000,0.024440,0.004415,1.224084e+02,0.000000
25%,4.75000,172.500000,43.000000,0.409217,0.073926,1.224084e+02,0.098849
50%,9.50000,258.800000,55.000000,1.114234,0.201289,1.224084e+02,0.167472
75%,14.25000,403.000000,62.250000,2.292258,0.414101,1.224084e+02,0.392947
max,19.00000,800.000000,67.000000,5.535500,1.000000,1.224084e+02,1.026074

In [ ]:
X = df[['TIME' ,'TEMPERATURE INLET']]
y = df[  'MOISTURE CONTENT']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
#Linear Regression
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
clf.score(X_test, y_test)
lr_MSE=mean_squared_error(y_test, y_pred),
lr_MAE= mean_absolute_error(y_test, y_pred)
lr_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
lr_R2=r2_score(y_test, y_pred)


results = pd.DataFrame()

tempResults = pd.DataFrame({'Algorithm':['Linear Regression Method'],'R2':[lr_R2] , 'MAE':[lr_MAE], 'MSE':[lr_MSE], 'RMSE':[lr_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

                  Algorithm        R2      MAE                   MSE      RMSE
0  Linear Regression Method  0.239355  0.88158  (0.904920528111777,)  0.951273

In [ ]:
#SVM
X = df[['TIME' ,'TEMPERATURE INLET']]
y = df[  'MOISTURE CONTENT']
from sklearn.svm import SVR
model = SVR()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y.values.reshape(-1,1))
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
#model.score(X_test, y_test)

SVR_MSE=mean_squared_error(y_test, y_pred),
SVR_MAE= mean_absolute_error(y_test, y_pred)
SVR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
SVR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Support Vector Regression'] , 'R2':[SVR_R2] , 'MAE':[SVR_MAE], 'MSE':[SVR_MSE], 'RMSE':[SVR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.239355,0.881580,"(0.904920528111777,)",0.951273
0,Support Vector Regression,0.843990,0.400339,"(0.22695569455741382,)",0.476399

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train) 
y_pred = regressor.predict(X_test)

RFR_MSE=mean_squared_error(y_test, y_pred),
RFR_MAE= mean_absolute_error(y_test, y_pred)
RFR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
RFR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Random Forest Regression'],'R2':[RFR_R2] , 'MAE':[RFR_MAE], 'MSE':[RFR_MSE], 'RMSE':[RFR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.239355,0.881580,"(0.904920528111777,)",0.951273
0,Support Vector Regression,0.843990,0.400339,"(0.22695569455741382,)",0.476399
0,Random Forest Regression,0.981584,0.160828,"(0.02679110990011346,)",0.163680

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor 
  
# create a regressor object
reg = DecisionTreeRegressor(random_state = 0) 
  
# fit the regressor with X and Y data
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)

DTR_MSE=mean_squared_error(y_test, y_pred),
DTR_MAE= mean_absolute_error(y_test, y_pred)
DTR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
DTR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Decision Tree Regression'],'R2':[RFR_R2] , 'MAE':[RFR_MAE], 'MSE':[RFR_MSE], 'RMSE':[RFR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.239355,0.881580,"(0.904920528111777,)",0.951273
0,Support Vector Regression,0.843990,0.400339,"(0.22695569455741382,)",0.476399
0,Random Forest Regression,0.981584,0.160828,"(0.02679110990011346,)",0.163680
0,Decision Tree Regression,0.981584,0.160828,"(0.02679110990011346,)",0.163680