<a href="https://colab.research.google.com/github/dileepchandhra/Solar-dryer/blob/main/MUSKMELON_NCipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('/content/drive/MyDrive/MINI PROJECT/Muskmelon-nc.csv')
df.head()
df['DRYING RATE'] = df['DRYING RATE'].fillna(df['DRYING RATE'].mean())

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TIME                      20 non-null     int64
 1   MASS                      20 non-null     float64
 2   TEMPERATURE INLET         20 non-null     int64
 3   INITIAL MOISTURE CONTENT  20 non-null     float64
 4   MOISTURE CONTENT          20 non-null     float64
 5   MOITURE RATIO             20 non-null     float64
 6   DRY MASS                  20 non-null     float64
 7   DRYING RATE               20 non-null     float64
dtypes: float64(6), int64(2)
memory usage: 1.4 KB

In [4]:
df.describe()

,TIME,MASS,TEMPERATURE INLET,INITIAL MOISTURE CONTENT,MOISTURE CONTENT,MOITURE RATIO,DRY MASS,DRYING RATE
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,2.000000e+01,20.000000
mean,9.50000,303.175000,50.200000,12.415616,4.084099,0.328949,5.963200e+01,0.645009
std,5.91608,239.345863,10.008418,0.000000,4.013715,0.323280,7.290015e-15,0.567888
min,0.00000,69.200000,32.000000,12.415616,0.160451,0.012923,5.963200e+01,0.000000
25%,4.75000,120.800000,41.750000,12.415616,1.025758,0.082618,5.963200e+01,0.275859
50%,9.50000,213.000000,52.500000,12.415616,2.571908,0.207151,5.963200e+01,0.545009
75%,14.25000,416.050000,57.250000,12.415616,5.976959,0.481407,5.963200e+01,0.866146
max,19.00000,800.000000,64.000000,12.415616,12.415616,1.000000,5.963200e+01,2.072713

In [5]:
X = df[['TIME' ,'TEMPERATURE INLET']]
y = df[  'MOISTURE CONTENT']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [6]:
#Linear Regression
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
clf.score(X_test, y_test)
lr_MSE=mean_squared_error(y_test, y_pred),
lr_MAE= mean_absolute_error(y_test, y_pred)
lr_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
lr_R2=r2_score(y_test, y_pred)


results = pd.DataFrame()

tempResults = pd.DataFrame({'Algorithm':['Linear Regression Method'],'R2':[lr_R2] , 'MAE':[lr_MAE], 'MSE':[lr_MSE], 'RMSE':[lr_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

                  Algorithm        R2      MAE                   MSE      RMSE
0  Linear Regression Method  0.859928  1.84704  (3.562675560103411,)  1.887505

In [7]:
#SVM
from sklearn.svm import SVR
model = SVR()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y.values.reshape(-1,1))
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
#model.score(X_test, y_test)

SVR_MSE=mean_squared_error(y_test, y_pred),
SVR_MAE= mean_absolute_error(y_test, y_pred)
SVR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
SVR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Support Vector Regression'] , 'R2':[SVR_R2] , 'MAE':[SVR_MAE], 'MSE':[SVR_MSE], 'RMSE':[SVR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.859928,1.847040,"(3.562675560103411,)",1.887505
0,Support Vector Regression,0.857639,0.358013,"(0.18433106410704048,)",0.429338

In [8]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train,y_train) 
y_pred = regressor.predict(X_test)

RFR_MSE=mean_squared_error(y_test, y_pred),
RFR_MAE= mean_absolute_error(y_test, y_pred)
RFR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
RFR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Random Forest Regression'],'R2':[RFR_R2] , 'MAE':[RFR_MAE], 'MSE':[RFR_MSE], 'RMSE':[RFR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.859928,1.847040,"(3.562675560103411,)",1.887505
0,Support Vector Regression,0.857639,0.358013,"(0.18433106410704048,)",0.429338
0,Random Forest Regression,0.992705,0.089245,"(0.009445146035720994,)",0.097186

In [9]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor 
  
# create a regressor object
reg = DecisionTreeRegressor(random_state = 0) 
  
# fit the regressor with X and Y data
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)

DTR_MSE=mean_squared_error(y_test, y_pred),
DTR_MAE= mean_absolute_error(y_test, y_pred)
DTR_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
DTR_R2=r2_score(y_test, y_pred)
tempResults = pd.DataFrame({'Algorithm':['Decision Tree Regression'],'R2':[RFR_R2] , 'MAE':[RFR_MAE], 'MSE':[RFR_MSE], 'RMSE':[RFR_RMSE] })
results = pd.concat([results, tempResults])
results = results[['Algorithm','R2', 'MAE','MSE','RMSE']]
results

,Algorithm,R2,MAE,MSE,RMSE
0,Linear Regression Method,0.859928,1.847040,"(3.562675560103411,)",1.887505
0,Support Vector Regression,0.857639,0.358013,"(0.18433106410704048,)",0.429338
0,Random Forest Regression,0.992705,0.089245,"(0.009445146035720994,)",0.097186
0,Decision Tree Regression,0.992705,0.089245,"(0.009445146035720994,)",0.097186